#!/bin/bash

#SBATCH --array=0-9
#SBATCH --partition=dept_gpu
#SBATCH --output=logs/train-0001_%j.out
#SBATCH --gres=gpu:1

OPERATION=$1

echo "performing ${OPERATION} benchmarking on fold: ${SLURM_ARRAY_TASK_ID}"

./benchmark ${SLURM_ARRAY_TASK_ID} ${OPERATION}
